### ISSUE TITLE
setup.sh: import cycle not allowed

### ISSUE THREAD

**Issue by tschoonj** [singularityhub/circle-ci#7]
Hi @vsoch 

I am running into trouble when setup.sh executes `go get -u github.com/golang/dep/cmd/dep`:

```shell
import cycle not allowed
package github.com/golang/dep/cmd/dep
	imports bytes
	imports errors
	imports runtime
	imports internal/bytealg
	imports internal/cpu
	imports runtime
Exited with code 1
```

You can also see this in my build at https://circleci.com/gh/DiamondLightSource/Savu/6

**Comment by vsoch** [comment]
I suspect it's because the install doesn't use modules anymore. Let me see if I can do a fix.

**Comment by vsoch** [comment]
I mean, *does* use modules. :)

**Comment by tschoonj** [comment]
Thanks for looking into this!

**Comment by vsoch** [comment]
Also, don't forget about the Singularity Orbs:

 - https://github.com/singularityhub/singularity-orb
 - https://circleci.com/orbs/registry/orb/singularity/singularity

They were generated from this original recipe, albeit it's fairly simple to just use this directly. For example usage, take a look at Singularity Python tests, and whatever other CircleCI projects I have that use Singularity :)

**Comment by vsoch** [comment]
Actually, I'll update the example here to use it :) It just passed testing, will merge asap.

**Comment by vsoch** [comment]
The config is updated and fixed, it now uses the Circle orbs and the user can specify the Singularity version, etc. https://circleci.com/gh/singularityhub/circle-ci/46

**Comment by tschoonj** [comment]
That looks awesome, will give it a go right away!

Thanks!
